# Generated by Django 4.2 on 2023-10-31 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='End_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('email', models.EmailField(default='No Mail', max_length=50, verbose_name='Email')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='User_Note')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Barcode')),
                ('des', models.CharField(max_length=200, verbose_name='Description')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('sku', models.CharField(max_length=50, verbose_name='Sku')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Vendor', verbose_name='Logo')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', ''), ('Pending', 'Pending'), ('Done', 'Done'), ('Delivered', 'Delivered')], default=('', ''), max_length=50, verbose_name='Req_Status')),
                ('client', models.CharField(choices=[('', ''), ('End_User', 'End_User'), ('Vendor', 'Vendor')], default=('', ''), max_length=50, verbose_name='client_kind')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='Received_Date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery_Date')),
                ('ref', models.CharField(default='No Num', max_length=25, verbose_name='REF_NUM')),
                ('End_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Request_client', to='Technical.end_user', verbose_name='End_User')),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Request_Vendor', to='Technical.vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Follow_Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect', models.CharField(choices=[('', ''), ('Phone', 'Phone'), ('WatsApp', 'WatsApp'), ('Messenger', 'Messenger')], default=('', ''), max_length=50, verbose_name='Connect')),
                ('msg_kind', models.CharField(choices=[('', ''), ('Pending_MSG', 'Pending_MSG'), ('Done_MSG', 'Done_MSG'), ('Delivered_MSG', 'Delivered_MSG'), ('FollowUP_MSG', 'FollowUP_MSG')], default=('', ''), max_length=50, verbose_name='Message')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('rate', models.CharField(choices=[('', ''), ('راضى', 'راضى'), ('غير_راضى', 'غير_راضى'), ('يحتاج_تطوير', 'يحتاج_تطوير')], default=('', ''), max_length=50, verbose_name='Rate')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_Follow_Up', to='Technical.request', verbose_name='Request')),
            ],
            options={
                'verbose_name_plural': 'Follow_Up',
            },
        ),
        migrations.CreateModel(
            name='Failer_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, verbose_name='S.N_IN')),
                ('active', models.CharField(choices=[('', ''), ('In_Warranty', 'In_Warranty'), ('Out_Warranty', 'Out_Warranty')], default=('', ''), max_length=25, verbose_name='Active')),
                ('invoice', models.ImageField(blank=True, null=True, upload_to='Invoice', verbose_name='invoice')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase_Date')),
                ('detail', models.CharField(default='Write Issue Detail', max_length=300, verbose_name='Detail')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Issue_name', to='Technical.issue', verbose_name='Issue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Failer_Detail_Product', to='Technical.product', verbose_name='Product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_Failer_Detail', to='Technical.request', verbose_name='Request')),
            ],
        ),
        migrations.CreateModel(
            name='Action_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, verbose_name='S.N_Out')),
                ('detail', models.CharField(default='Write Action Detail', max_length=300, verbose_name='Detail')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost')),
                ('note', models.CharField(default='No Note', max_length=50, verbose_name='Note')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Action_name', to='Technical.action', verbose_name='Action')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Action_Detail_Product', to='Technical.product', verbose_name='Product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_Action_Detail', to='Technical.request', verbose_name='Request')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Action_Technician', to='Technical.technician', verbose_name='Technician')),
            ],
        ),
    ]
