# Generated by Django 4.2 on 2023-10-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_detail',
            name='detail',
            field=models.CharField(default='Write Action Detail', max_length=300, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='failer_detail',
            name='detail',
            field=models.CharField(default='Write Issue Detail', max_length=300, verbose_name='Detail'),
        ),
    ]
