# Generated by Django 4.2 on 2023-10-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
