# Generated by Django 4.2 on 2023-11-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField(max_length=500, verbose_name='Complain')),
                ('Report', models.TextField(max_length=500, verbose_name='Report')),
                ('advice', models.CharField(max_length=200, verbose_name='Advice')),
                ('note', models.CharField(max_length=50, verbose_name='Note')),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_Report', to='Technical.request', verbose_name='Request')),
            ],
        ),
    ]
