# Generated by Django 4.2 on 2023-10-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Technical", "0002_alter_action_detail_detail_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="end_user",
            options={},
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={},
        ),
        migrations.RemoveField(
            model_name="request",
            name="note",
        ),
        migrations.AddField(
            model_name="request",
            name="ref",
            field=models.CharField(
                default="No Num", max_length=25, verbose_name="REF_NUM"
            ),
        ),
        migrations.AlterField(
            model_name="action_detail",
            name="serial",
            field=models.CharField(max_length=50, verbose_name="S.N_Out"),
        ),
        migrations.AlterField(
            model_name="end_user",
            name="email",
            field=models.EmailField(
                default="No Mail", max_length=50, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="end_user",
            name="note",
            field=models.CharField(
                default="No Note", max_length=50, verbose_name="User_Note"
            ),
        ),
        migrations.AlterField(
            model_name="failer_detail",
            name="serial",
            field=models.CharField(max_length=50, verbose_name="S.N_IN"),
        ),
        migrations.AlterField(
            model_name="request",
            name="End_User",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Request_client",
                to="Technical.end_user",
                verbose_name="End_User",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="client",
            field=models.CharField(
                choices=[("", ""), ("End_User", "End_User"), ("Vendor", "Vendor")],
                default=("", ""),
                max_length=50,
                verbose_name="client_kind",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Pending", "Pending"),
                    ("Done", "Done"),
                    ("Delivered", "Delivered"),
                ],
                default=("", ""),
                max_length=50,
                verbose_name="Req_Status",
            ),
        ),
    ]
