# Generated by Django 4.2 on 2023-11-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0002_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action_detail',
            old_name='serial',
            new_name='serial_out',
        ),
        migrations.RenameField(
            model_name='failer_detail',
            old_name='serial',
            new_name='serial_in',
        ),
    ]
