# Generated by Django 4.2 on 2023-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0003_rename_serial_action_detail_serial_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failer_detail',
            name='ref',
        ),
        migrations.AddField(
            model_name='action_detail',
            name='ref',
            field=models.CharField(default='No_Ref', max_length=25, verbose_name='REF_NUM'),
        ),
    ]
