# Generated by Django 4.2 on 2023-11-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technical', '0004_remove_failer_detail_ref_action_detail_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='advice',
            field=models.TextField(max_length=500, verbose_name='Advice'),
        ),
    ]
