# Generated by Django 4.2 on 2023-10-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0, max_length=15, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.CharField(choices=[('In_Warranty', 'In_Warranty'), ('Out_Warranty', 'Out_Warranty')], default=('In_Warranty', 'In_Warranty'), max_length=50, verbose_name='Active'),
        ),
    ]
