# Generated by Django 4.2 on 2023-10-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_order_cost_alter_order_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
